=== aptree-labs/campaign-registry/platform.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#", 
    "type": "object",
    "properties": {
        "id": {"type": "string"},
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "image": {
            "type": "string"
        },
        "link": {
            "type": "string"
        },
        "bio": {
            "type": "string"
        },
        "socials": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "platform": {"type": "string"},
                    "link": {"type": "string"}
                },
                "required": [
                    "platform",
                    "link"
                ]
            }
        },
        "categories": {
            "type": "array", 
            "items": {
                "type": "string"
            }
        },
        "scheduled_highlights": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "from": {"type": "number"},
                    "to": {"type": "number"}
                },
                "required": ["from", "to"]
            }
        },
        "rank": {
            "type": "string",
            "enum": [
                "legendary",
                "premier",
                "featured",
                "verified",
                "listed"
            ]
        }
    },
    "required": ["id", "name", "description", "image", "link", "socials", "categories","bio", "rank"]
}

=== aptree-labs/campaign-registry/platforms/guiinu.platform.json
{
    "id": "guiinu",
    "name": "Gui Inu",
    "description": "Buy tickets, join the draw and win BIG!",
    "image": "guiinu.png",
    "link": "https://www.guiinu.com",
    "bio": "",
    "socials": [
        {
            "link": "https://x.com/guiinuonaptos",
            "platform": "x"
        },
        {
            "link": "https://discord.com/invite/4UESwMp8cK",
            "platform": "discord"
        }
    ],
    "categories": [
        "community",
        "meme",
        "token"
    ],
    "rank": "premier",
    "scheduled_highlights": []
}

=== aptree-labs/campaign-registry/platforms/thala.platform.json
{
    "id": "thala",
    "name": "Thala Labs",
    "description": "DeFi HyperApp - Powered by Move, Now Live on Aptos",
    "image": "thala-logo.avif",
    "link": "https://www.thala.fi/",
    "bio": "Thala is a decentralized finance protocol, enabling seamless borrowing of a decentralized, over-collateralized stablecoin named Move Dollar and capital-efficient liquidity provisioning via a rebalancing AMM.",
    "rank": "listed",
    "categories": ["defi"],
    "socials": [
        {
            "platform": "x",
            "link": "https://twitter.com/ThalaLabs"
        },
        {
            "platform": "discord",
            "link": "https://discord.gg/thala"
        }
    ],
    "scheduled_highlights": []
}

=== aptree-labs/campaign-registry/platforms/earnium.platform.json
{
    "id": "earnium",
    "name": "Earnium",
    "description": "Earnium is a DEX built to unlock Billion $ trading volume",
    "image": "earnium.avif",
    "link": "https://app.earnium.io/",
    "bio": "Earnium is a DEX built to unlock Billion $ trading volume",
    "socials": [
        {
            "link": "https://x.com/earnium_io",
            "platform": "x"
        },
        {
            "link": "https://discord.gg/jAQrgdZCkq",
            "platform": "discord"
        }
    ],
    "rank": "listed",
    "categories": ["defi"],
    "scheduled_highlights": []
}

=== aptree-labs/campaign-registry/platforms/tapp.platform.json
{
    "id": "tapp",
    "name": "Tapp Exchange",
    "description": "Unlocking Liquidity-as-a-Service via Next-Gen V4 DEX Technology.",
    "image": "tapp.png",
    "link": "https://tapp.exchange/",
    "bio": "TAPP is the first DEX on Aptos to bring Uniswap V4-style features, delivering next-generation liquidity infrastructure tailored for modular DeFi. With programmable smart contract hooks, protocols can fully customize their LP pools—adjusting fees, rewards, and oracles to fit unique use cases. TAPP also introduces flash accounting for more efficient swaps, enabling capital-efficient features like margin-leveraged pools while reducing transaction overhead.\nIts in-built Active Liquidity Management (ALM) system, combined with AI-powered routing and DEX aggregation, ensures best-price execution and optimized returns for LPs. TAPP isn't just a DEX—it’s a scalable, composable liquidity layer for the entire Aptos ecosystem. With ve(3,3) mechanics and compounding network effects from each new integration, TAPP builds a self-reinforcing moat that strengthens with every protocol onboarded.",
    "socials": [
        {
            "platform": "x",
            "link": "https://x.com/TappExchange"
        }
    ],
    "rank": "listed",
    "categories": ["defi"],
    "scheduled_highlights": []
}

=== aptree-labs/campaign-registry/platforms/petra.platform.json
{
    "id": "petra",
    "name": "Petra Wallet",
    "description": "A web3 wallet to explore Aptos by Aptos Labs",
    "image": "petra-logo-2.png",
    "link": "https://petra.app/",
    "socials": [
        {
            "link": "https://twitter.com/PetraWallet",
            "platform": "x"
        },
        {
            "link": "https://discord.gg/4FQjUq2aK9",
            "platform": "discord"
        }
    ],
    "categories": ["defi"],
    "bio": "Petra makes it easy to store your assets, transact with friends, and connect with apps on the Aptos blockchain.\nOur industry-leading partners and Aptos’ scalable, lightning-fast protocol lets you buy APT, send tokens and experience the magic of web3 in moments.\nSafely store and manage all your assets in Petra, a self-custodial wallet. Whether it’s the latest NFT drop, a prized collectible, or any other token - we support it all.",
    "rank": "legendary",
    "scheduled_highlights": []
}

=== aptree-labs/campaign-registry/platforms/echelon.platform.json
{
    "id": "echelon",
    "name": "Echelon",
    "description": "Efficient Move Money Markets",
    "image": "echelon-logo.avif",
    "link": "https://echelon.market/",
    "socials": [
        {
            "link": "https://x.com/echelonmarket",
            "platform": "x"
        },
        {
            "link": "https://discord.gg/echelonmarket",
            "platform": "discord"
        }
    ],
    "rank": "listed",
    "bio": "Echelon is a high-efficiency borrow/lend market designed to scale Move DeFi & liquidity. Drawing inspiration from AAVE's E-Mode, Echelon offers unmatched capital efficiency to borrowers with high LTV loans on select asset pairs, such as stables or LST and native assets.\nEchelon v1 is audited and live on Aptos mainnet as of March with plans to expand to other Move VMs such as Movement's M2 and Initia in 2024. v1.1 will support RWA collateral (i.e. Ondo's USDY) and covered call options vaults. ",
    "categories": ["defi"],
    "scheduled_highlights": [

    ]
}

=== aptree-labs/campaign-registry/platforms/merkle.platform.json
{
    "id": "merkle",
    "name": "Merkle",
    "description": "Seamless decentralised Perpetuals",
    "image": "merkle-logo.jpg",
    "link": "https://app.merkle.trade/",
    "bio": "Seamless decentralised Perpetuals",
    "rank": "premier",
    "categories": ["defi"],
    "scheduled_highlights": [],
    "socials": [
        {
            "link": "https://x.com/Merkle_Trade",
            "platform": "x"
        },
        {
            "link": "https://discord.gg/merkle-trade",
            "platform": "discord"
        }
    ]
}

=== aptree-labs/campaign-registry/platforms/kana-labs.platform.json
{
    "id": "kana-labs",
    "name": "Xyra Labs",
    "description": "User friendly super-app for DeFi - Crosschain swaps & CLOB-based fully on-chain Perps",
    "image": "xyra-labs.jpg",
    "link": "https://www.xyra.trade/?market=BTC-PERP",
    "bio": "A NetMarble and Jump Crypto project, Kana Labs is building the next-gen cross-chain ecosystem of DeFi, GameFi & NFTs.\nWe have built a core foundation layer of aggregated bridges and blockchains on which the next-gen tools for DeFi and Gamefi would be built - an ecosystem for seamless transactions, a layer-1 for Web3 and games to bridge through.\nLastly, we have the cheapest + fastest swap rates across on our dapp. Our smart wallet features - AA (Account Abstraction), social logins and everything customised.",
    "categories": ["defi"],
    "rank": "premier",
    "scheduled_highlights": [],
    "socials": [
        {
            "link": "https://x.com/xyralabs_",
            "platform": "x"
        },
        {
            "link": "https://discord.com/invite/zgMJEgVt38",
            "platform": "discord"
        }
    ]
}
