=== aptree-labs/campaign-registry/platform.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#", 
    "type": "object",
    "properties": {
        "id": {"type": "string"},
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "image": {
            "type": "string"
        },
        "link": {
            "type": "string"
        },
        "bio": {
            "type": "string"
        },
        "socials": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "platform": {"type": "string"},
                    "link": {"type": "string"}
                },
                "required": [
                    "platform",
                    "link"
                ]
            }
        },
        "categories": {
            "type": "array", 
            "items": {
                "type": "string"
            }
        },
        "scheduled_highlights": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "from": {"type": "number"},
                    "to": {"type": "number"}
                },
                "required": ["from", "to"]
            }
        },
        "rank": {
            "type": "string",
            "enum": [
                "legendary",
                "premier",
                "featured",
                "verified",
                "listed"
            ]
        }
    },
    "required": ["id", "name", "description", "image", "link", "socials", "categories","bio", "rank"]
}

=== aptree-labs/campaign-registry/platforms/aptos-names-service.platform.json
{
    "id": "aptos-names-service",
    "name": "Aptos Names Service",
    "description": "Register your aptos domain",
    "image": "aptos-names-service.png",
    "link": "https://www.aptosnames.com/",
    "socials": [],
    "bio": "",
    "categories": [],
    "rank": "listed",
    "scheduled_highlights": []
}
